export const ActionTypes = {
  SET_BOOKS: "SET_BOOKS",
  SET_FILTERED_BOOKS: "SET_FILTERED_BOOKS",
  SET_CART_BOOKS:"SET_CART_BOOKS",
  DELETE_CART_BOOK:"DELETE_CART_BOOK",
  UPDATE_CART_QUANTITY:"UPDATE_CART_QUANTITY"
};